# Generated by Django 3.1.6 on 2021-02-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True, verbose_name='種別')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'db_table': 'promotion_category',
            },
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(verbose_name='章')),
                ('chapter_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='章タイトル')),
                ('clause', models.IntegerField(verbose_name='節')),
                ('clause_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='節タイトル')),
                ('sections', models.IntegerField(verbose_name='項')),
                ('document', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '細目',
                'verbose_name_plural': '細目',
                'db_table': 'promotion_contents',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255, unique=True, verbose_name='部門')),
            ],
            options={
                'verbose_name': '部門',
                'verbose_name_plural': '部門',
                'db_table': 'promotion_section',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_from', models.IntegerField(verbose_name='部門from')),
                ('section_to', models.IntegerField(verbose_name='部門to')),
                ('subject_name', models.CharField(max_length=255, verbose_name='名前')),
                ('subject_image', models.ImageField(blank=True, null=True, upload_to='static/handbook/img/', verbose_name='画像')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handbook.category', verbose_name='種別')),
            ],
            options={
                'verbose_name': '課目',
                'verbose_name_plural': '課目',
                'db_table': 'promotion_subject',
            },
        ),
        migrations.AddField(
            model_name='contents',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handbook.subject', verbose_name='名前'),
        ),
    ]
