# Generated by Django 3.1.6 on 2021-05-09 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_date', models.DateField(verbose_name='修了日')),
                ('signature', models.CharField(max_length=255, verbose_name='サイン')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handbook.subject', verbose_name='修得課目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': '課目記録',
                'verbose_name_plural': '課目記録',
                'db_table': 'promotion_subject_records',
            },
        ),
        migrations.CreateModel(
            name='ContentsRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_date', models.DateField(verbose_name='修了日')),
                ('signature', models.CharField(max_length=255, verbose_name='サイン')),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handbook.contents', verbose_name='細目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': '細目記録',
                'verbose_name_plural': '細目記録',
                'db_table': 'promotion_contents_records',
            },
        ),
        migrations.AddConstraint(
            model_name='subjectrecords',
            constraint=models.UniqueConstraint(fields=('user', 'subject'), name='subject_records_unique'),
        ),
        migrations.AddConstraint(
            model_name='contentsrecords',
            constraint=models.UniqueConstraint(fields=('user', 'contents'), name='contents_records_unique'),
        ),
    ]
