# Generated by Django 3.1.6 on 2021-06-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_auto_20210509_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='contents_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='細目数'),
        ),
    ]
