# Generated by Django 3.1.6 on 2021-06-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_auto_20210621_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrecords',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record', to='handbook.subject', verbose_name='修得課目'),
        ),
    ]
