# Generated by Django 3.1.6 on 2021-06-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0006_auto_20210625_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsrecords',
            name='contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents_record', to='handbook.contents', verbose_name='細目'),
        ),
        migrations.AlterField(
            model_name='subjectrecords',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_record', to='handbook.subject', verbose_name='修得課目'),
        ),
    ]
