# Generated by Django 3.1.6 on 2021-07-02 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handbook', '0007_auto_20210625_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbook.subject', verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='contentsrecords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbook.category', verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='subjectrecords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
    ]
