# Generated by Django 3.1.6 on 2021-10-12 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handbook', '0008_auto_20210702_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(verbose_name='種別')),
                ('promise_date', models.DateField(verbose_name='約束した日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='名前')),
            ],
            options={
                'verbose_name': '約束',
                'verbose_name_plural': '約束',
                'db_table': 'promotion_promise',
            },
        ),
        migrations.AddConstraint(
            model_name='promise',
            constraint=models.UniqueConstraint(fields=('user', 'chapter'), name='promise_unique'),
        ),
    ]
